# Generated by Django 2.2 on 2019-04-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'ชาย'), ('F', 'หญิง'), ('X', 'อื่นๆ')], max_length=5),
        ),
    ]
